name: 'Deploy word press to app service action'
description: 'Greet someone and record the time'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to login to azure'
    required: true
  tenant-id:
    description: 'Tenant id to login to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  resource-group-name:
    description: 'Resource group to deploy your resources to'
    required: true
  clientSecret:
    decription: 'App secret to login to azure'
    required: true
#runs:
  # using: 'node20'
  # main: 'dist/index.js'
runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3
    - name: 'az cli login'
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ inputs.client-id }}","clientSecret":"${{ inputs.clientSecret }}","subscriptionId":"${{ inputs.subscription-id }}","tenantId":"${{ inputs.tenant-id }}"}'
    - name: 'Az deploy - wordpress on app svc'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: '9992ee4c-bf90-4d14-9ebe-08efa6dce299'
        resourceGroupName: 'action-rg'
        template: https://raw.githubusercontent.com/vaibbavisk20/simple_react_app/main/template.json
        parameters: https://raw.githubusercontent.com/vaibbavisk20/simple_react_app/main/parameters.json
        failOnStdErr: false
