name: 'My Workflow'

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Print Message Action
        uses: vaibbavisk20/hello-world-composite-action@v6
